# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CafePrices' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CafePrices
  
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'FirebaseUI/Storage'
pod 'Nuke', '~> 9.0'

  target 'CafePricesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CafePricesUITests' do
    # Pods for testing
  end

end
